import { writeFileSync, mkdirSync } from "node:fs"
import { dirname } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = `${__dirname}/../data/stays.json`

const SHARED = "/images/shared"
const gallery = (slug) => [
  `/images/stays/${slug}/cover.png`,
  `${SHARED}/gallery-pool.png`,
  `${SHARED}/gallery-bedroom.png`,
  `${SHARED}/gallery-living.png`,
  `${SHARED}/gallery-bathroom.png`,
  `${SHARED}/gallery-dining.png`,
  `${SHARED}/gallery-garden.png`,
  `${SHARED}/gallery-beach.png`,
  `${SHARED}/gallery-exterior.png`,
]

const WA = "+919876543210"

// Builds standard + season pricing (season = 2x standard) from a list of room defs.
function pricing(rooms) {
  const standardRooms = rooms.map((r) => ({ type: r.type, pricePerNight: r.price, maxGuests: r.guests }))
  const seasonRooms = rooms.map((r) => ({ type: r.type, pricePerNight: r.price * 2, maxGuests: r.guests }))
  return {
    standard: { label: "Standard (Feb–Oct)", roomTypes: standardRooms },
    season: {
      label: "Peak Season (Nov, Dec, Jan)",
      note: "Rates typically double during Goa's peak tourist season (November–January).",
      roomTypes: seasonRooms,
    },
    currency: "INR",
    minStay: 1,
    displayPrice: Math.min(...standardRooms.map((r) => r.pricePerNight)),
  }
}

function breadcrumbs(stay, typeLabel, typeUrl) {
  return [
    { name: "Home", url: "/" },
    { name: "All Stays", url: "/all-stays" },
    { name: typeLabel, url: typeUrl },
    { name: stay.name, url: `/stays/${stay.slug}` },
  ]
}

const reviewsFor = (name) => [
  {
    id: "rev-1",
    name: "Priya Sharma",
    rating: 5,
    review: `${name} exceeded every expectation. The space was spotless, the views unreal, and the host was responsive at every step. We never wanted to leave.`,
    date: "2024-12-15",
    location: "Mumbai",
    verified: true,
  },
  {
    id: "rev-2",
    name: "Arjun Mehta",
    rating: 5,
    review: `Booking through Goa Beach Stays was effortless. ${name} was exactly as pictured — genuinely one of the best stays we have had in Goa.`,
    date: "2024-11-28",
    location: "Bengaluru",
    verified: true,
  },
  {
    id: "rev-3",
    name: "Sneha & Rohit",
    rating: 4,
    review: `Loved our time at ${name}. Beautiful property, great location, and the team was always a WhatsApp message away. Would happily return.`,
    date: "2024-10-09",
    location: "Pune",
    verified: true,
  },
]

const villaAmenities = [
  "Private Pool",
  "Free WiFi",
  "Air Conditioning",
  "Fully Equipped Kitchen",
  "Free Parking",
  "BBQ Area",
  "Outdoor Seating",
  "Daily Housekeeping",
  "24/7 Caretaker",
  "Smart TV",
]
const resortAmenities = [
  "Swimming Pool",
  "Free WiFi",
  "Air Conditioning",
  "In-house Restaurant",
  "Free Parking",
  "Room Service",
  "Garden",
  "Daily Housekeeping",
  "Front Desk",
  "Laundry Service",
]

const seeds = [
  {
    slug: "azure-pool-villa-calangute",
    type: "villa",
    category: ["pool", "luxury", "family", "north-goa"],
    name: "Azure Pool Villa",
    tagline: "A Sun-Drenched Private Pool Retreat in the Heart of Calangute",
    area: "North Goa, Calangute",
    district: "North Goa",
    address: "Near Calangute–Candolim Road, Calangute, North Goa, Goa 403516",
    postalCode: "403516",
    lat: 15.5439,
    lng: 73.7553,
    nearestBeach: "Calangute Beach (0.5 km)",
    nearestAirport: "Dabolim Airport (45 km)",
    rooms: [
      { type: "Garden Bedroom", price: 28000, guests: 2 },
      { type: "Pool-Facing Suite", price: 34000, guests: 3 },
    ],
    roomsCount: 4,
    maxGuests: 10,
    bedrooms: 4,
    bathrooms: 4,
    amenities: villaAmenities,
    highlights: [
      "Large private swimming pool with sundeck",
      "Just 500m from buzzing Calangute Beach",
      "Spacious open-plan living for families",
      "Fully staffed with a dedicated caretaker",
    ],
    tags: ["Pool", "Luxury", "Family", "North Goa", "Calangute"],
    nearbyAttractions: [
      "Calangute Beach – 0.5 km",
      "Baga Beach – 2.5 km",
      "Saturday Night Market – 6 km",
      "Fort Aguada – 9 km",
    ],
    typeLabel: "Luxury Villas North Goa",
    typeUrl: "/luxury-villas-north-goa",
    featured: true,
  },
  {
    slug: "palm-haven-resort-baga",
    type: "resort",
    category: ["pool", "boutique", "north-goa"],
    name: "Palm Haven Resort",
    tagline: "A Laid-Back Boutique Resort Moments from Baga Beach",
    area: "North Goa, Baga",
    district: "North Goa",
    address: "Baga Beach Road, Baga, North Goa, Goa 403516",
    postalCode: "403516",
    lat: 15.5553,
    lng: 73.7517,
    nearestBeach: "Baga Beach (0.4 km)",
    nearestAirport: "Dabolim Airport (47 km)",
    rooms: [
      { type: "Deluxe Room", price: 3500, guests: 2 },
      { type: "Premium Room", price: 4500, guests: 2 },
      { type: "Family Suite", price: 6000, guests: 4 },
    ],
    roomsCount: 18,
    maxGuests: 50,
    bedrooms: 18,
    bathrooms: 18,
    amenities: resortAmenities,
    highlights: [
      "Palm-fringed pool at the centre of the resort",
      "Walking distance to Baga's shacks and nightlife",
      "In-house multi-cuisine restaurant",
      "Ideal for groups and families",
    ],
    tags: ["Pool", "Boutique", "North Goa", "Baga"],
    nearbyAttractions: [
      "Baga Beach – 0.4 km",
      "Tito's Lane – 0.8 km",
      "Calangute Beach – 2.5 km",
      "Anjuna Flea Market – 7 km",
    ],
    typeLabel: "North Goa Resorts",
    typeUrl: "/north-goa-resorts",
    featured: true,
  },
  {
    slug: "terra-rossa-resort-palolem",
    type: "resort",
    category: ["heritage", "garden", "south-goa", "boutique"],
    name: "Terra Rossa Resort",
    tagline: "Where Portuguese Heritage Meets Tropical Luxury",
    area: "South Goa, Palolem",
    district: "South Goa",
    address: "Near Palolem Beach, Canacona, South Goa, Goa 403702",
    postalCode: "403702",
    lat: 15.0097,
    lng: 74.0231,
    nearestBeach: "Palolem Beach (0.3 km)",
    nearestAirport: "Dabolim Airport (67 km)",
    rooms: [
      { type: "Deluxe Room", price: 4000, guests: 2 },
      { type: "Premium Room", price: 5000, guests: 2 },
      { type: "Heritage Suite", price: 6500, guests: 3 },
    ],
    roomsCount: 6,
    maxGuests: 20,
    bedrooms: 6,
    bathrooms: 6,
    amenities: resortAmenities,
    highlights: [
      "Restored Portuguese-era heritage architecture",
      "300m from scenic Palolem Beach",
      "Half an acre of lush tropical garden",
      "Intimate, boutique, personally run",
    ],
    tags: ["Heritage", "South Goa", "Palolem", "Pool", "Garden", "Boutique"],
    nearbyAttractions: [
      "Palolem Beach – 0.3 km",
      "Butterfly Beach – 4 km",
      "Rajbagh Beach – 2 km",
      "Cotigao Wildlife Sanctuary – 12 km",
    ],
    typeLabel: "South Goa Resorts",
    typeUrl: "/south-goa-resorts",
    featured: true,
  },
  {
    slug: "serenity-villa-vagator",
    type: "villa",
    category: ["beachfront", "pool", "couple", "north-goa"],
    name: "Serenity Villa",
    tagline: "A Clifftop Beachfront Villa Built for Two",
    area: "North Goa, Vagator",
    district: "North Goa",
    address: "Ozran Cliff Road, Vagator, North Goa, Goa 403509",
    postalCode: "403509",
    lat: 15.5984,
    lng: 73.7441,
    nearestBeach: "Ozran (Little Vagator) Beach (0.2 km)",
    nearestAirport: "Dabolim Airport (50 km)",
    rooms: [
      { type: "Sea-View Master", price: 32000, guests: 2 },
      { type: "Garden Bedroom", price: 28000, guests: 2 },
    ],
    roomsCount: 2,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: villaAmenities,
    highlights: [
      "Perched on Vagator cliff with sea views",
      "Private infinity pool overlooking the ocean",
      "Steps from Ozran Beach",
      "Intimate, romantic, couples-focused",
    ],
    tags: ["Beachfront", "Pool", "Couple", "North Goa", "Vagator"],
    nearbyAttractions: [
      "Ozran Beach – 0.2 km",
      "Chapora Fort – 2 km",
      "Anjuna Beach – 4 km",
      "Thalassa Greek Restaurant – 1 km",
    ],
    typeLabel: "Luxury Villas North Goa",
    typeUrl: "/luxury-villas-north-goa",
    featured: true,
  },
  {
    slug: "blue-lagoon-cottage-morjim",
    type: "cottage",
    category: ["beachfront", "budget", "north-goa"],
    name: "Blue Lagoon Cottage",
    tagline: "A Rustic Beach Cottage on Quiet Morjim Sands",
    area: "North Goa, Morjim",
    district: "North Goa",
    address: "Morjim Beach Road, Morjim, North Goa, Goa 403512",
    postalCode: "403512",
    lat: 15.6303,
    lng: 73.7339,
    nearestBeach: "Morjim Beach (0.1 km)",
    nearestAirport: "Dabolim Airport (55 km)",
    rooms: [
      { type: "Garden Cottage", price: 3000, guests: 2 },
      { type: "Beach-View Cottage", price: 4200, guests: 2 },
    ],
    roomsCount: 5,
    maxGuests: 12,
    bedrooms: 5,
    bathrooms: 5,
    amenities: [
      "Free WiFi",
      "Air Conditioning",
      "Beach Access",
      "Free Parking",
      "Outdoor Seating",
      "Hammocks",
      "Daily Housekeeping",
      "Caretaker on Site",
    ],
    highlights: [
      "Directly on tranquil Morjim Beach",
      "Laid-back bohemian atmosphere",
      "Great value beachfront stay",
      "Famous for turtle-nesting shores",
    ],
    tags: ["Beachfront", "Budget", "North Goa", "Morjim"],
    nearbyAttractions: [
      "Morjim Beach – 0.1 km",
      "Ashvem Beach – 2 km",
      "Chapora River – 3 km",
      "Mandrem Beach – 4 km",
    ],
    typeLabel: "North Goa Stays",
    typeUrl: "/north-goa-stays",
    featured: false,
  },
  {
    slug: "heritage-house-panjim",
    type: "homestay",
    category: ["heritage", "portuguese", "city", "budget"],
    name: "Heritage House Panjim",
    tagline: "A Restored Portuguese Townhouse in Old Fontainhas",
    area: "Panjim, Fontainhas",
    district: "North Goa",
    address: "31st January Road, Fontainhas, Panjim, Goa 403001",
    postalCode: "403001",
    lat: 15.4989,
    lng: 73.8278,
    nearestBeach: "Miramar Beach (3 km)",
    nearestAirport: "Dabolim Airport (29 km)",
    rooms: [
      { type: "Heritage Room", price: 3500, guests: 2 },
      { type: "Balcony Room", price: 4500, guests: 2 },
    ],
    roomsCount: 4,
    maxGuests: 8,
    bedrooms: 4,
    bathrooms: 4,
    amenities: [
      "Free WiFi",
      "Air Conditioning",
      "Breakfast Included",
      "Heritage Interiors",
      "Common Lounge",
      "Daily Housekeeping",
      "Host on Site",
      "City-Centre Location",
    ],
    highlights: [
      "Set in Panjim's Latin Quarter, Fontainhas",
      "Authentic Portuguese-Goan interiors",
      "Walkable to cafes, galleries and churches",
      "Perfect for culture-led city stays",
    ],
    tags: ["Heritage", "Portuguese", "Panjim", "City", "Homestay"],
    nearbyAttractions: [
      "Fontainhas Latin Quarter – on doorstep",
      "Our Lady of the Immaculate Conception Church – 0.8 km",
      "Miramar Beach – 3 km",
      "Old Goa Churches – 10 km",
    ],
    typeLabel: "Stays in Panjim",
    typeUrl: "/stays-in-panjim",
    featured: false,
  },
  {
    slug: "ocean-breeze-villa-cavelossim",
    type: "villa",
    category: ["beachfront", "pool", "south-goa", "family"],
    name: "Ocean Breeze Villa",
    tagline: "A Beachfront Family Villa on South Goa's Golden Sands",
    area: "South Goa, Cavelossim",
    district: "South Goa",
    address: "Mobor Beach Road, Cavelossim, South Goa, Goa 403731",
    postalCode: "403731",
    lat: 15.1722,
    lng: 73.9442,
    nearestBeach: "Cavelossim Beach (0.2 km)",
    nearestAirport: "Dabolim Airport (38 km)",
    rooms: [
      { type: "Garden Bedroom", price: 27000, guests: 2 },
      { type: "Sea-View Suite", price: 33000, guests: 3 },
    ],
    roomsCount: 4,
    maxGuests: 10,
    bedrooms: 4,
    bathrooms: 4,
    amenities: villaAmenities,
    highlights: [
      "Steps from quiet Cavelossim Beach",
      "Large private pool facing the sea",
      "Spacious, family-friendly layout",
      "Close to Mobor's riverside restaurants",
    ],
    tags: ["Beachfront", "Pool", "South Goa", "Cavelossim", "Family"],
    nearbyAttractions: [
      "Cavelossim Beach – 0.2 km",
      "Mobor Beach – 1 km",
      "Sal River – 2 km",
      "Varca Beach – 5 km",
    ],
    typeLabel: "Luxury Villas South Goa",
    typeUrl: "/luxury-villas-south-goa",
    featured: true,
  },
  {
    slug: "bougainvillea-resort-anjuna",
    type: "resort",
    category: ["pool", "garden", "boutique", "north-goa"],
    name: "Bougainvillea Resort",
    tagline: "A Blooming Garden Resort in Bohemian Anjuna",
    area: "North Goa, Anjuna",
    district: "North Goa",
    address: "Anjuna Beach Road, Anjuna, North Goa, Goa 403509",
    postalCode: "403509",
    lat: 15.5736,
    lng: 73.7407,
    nearestBeach: "Anjuna Beach (0.6 km)",
    nearestAirport: "Dabolim Airport (49 km)",
    rooms: [
      { type: "Deluxe Room", price: 4500, guests: 2 },
      { type: "Garden Suite", price: 6000, guests: 3 },
    ],
    roomsCount: 12,
    maxGuests: 30,
    bedrooms: 12,
    bathrooms: 12,
    amenities: resortAmenities,
    highlights: [
      "Pool framed by vivid bougainvillea",
      "Close to the famous Anjuna Flea Market",
      "Boutique scale with personal service",
      "Whitewashed villas and rattan interiors",
    ],
    tags: ["Pool", "Garden", "Boutique", "North Goa", "Anjuna"],
    nearbyAttractions: [
      "Anjuna Beach – 0.6 km",
      "Anjuna Flea Market – 1 km",
      "Chapora Fort – 3 km",
      "Vagator Beach – 4 km",
    ],
    typeLabel: "Boutique Resorts Goa",
    typeUrl: "/boutique-resorts-goa",
    featured: true,
  },
  {
    slug: "jungle-nest-villa-mandrem",
    type: "villa",
    category: ["jungle", "pool", "luxury", "north-goa"],
    name: "Jungle Nest Villa",
    tagline: "A Secluded Forest Hideaway Above Mandrem",
    area: "North Goa, Mandrem",
    district: "North Goa",
    address: "Junas Wada, Mandrem, North Goa, Goa 403527",
    postalCode: "403527",
    lat: 15.6483,
    lng: 73.7039,
    nearestBeach: "Mandrem Beach (1.2 km)",
    nearestAirport: "Dabolim Airport (58 km)",
    rooms: [
      { type: "Canopy Bedroom", price: 30000, guests: 2 },
      { type: "Forest Suite", price: 36000, guests: 3 },
    ],
    roomsCount: 3,
    maxGuests: 8,
    bedrooms: 3,
    bathrooms: 3,
    amenities: villaAmenities,
    highlights: [
      "Immersed in dense tropical forest",
      "Private pool reflecting the green canopy",
      "Total privacy and birdsong serenity",
      "A short drive from Mandrem Beach",
    ],
    tags: ["Jungle", "Pool", "Luxury", "North Goa", "Mandrem"],
    nearbyAttractions: [
      "Mandrem Beach – 1.2 km",
      "Ashvem Beach – 3 km",
      "Arambol Beach – 5 km",
      "Sweet Water Lake – 6 km",
    ],
    typeLabel: "Jungle Villas Goa",
    typeUrl: "/jungle-villas-goa",
    featured: true,
  },
  {
    slug: "sunset-cottage-agonda",
    type: "cottage",
    category: ["beachfront", "budget", "south-goa", "couple"],
    name: "Sunset Cottage",
    tagline: "A Romantic Beach Cottage on Pristine Agonda",
    area: "South Goa, Agonda",
    district: "South Goa",
    address: "Agonda Beach Road, Canacona, South Goa, Goa 403702",
    postalCode: "403702",
    lat: 15.0436,
    lng: 74.0119,
    nearestBeach: "Agonda Beach (0.1 km)",
    nearestAirport: "Dabolim Airport (63 km)",
    rooms: [
      { type: "Beach Cottage", price: 3200, guests: 2 },
      { type: "Sea-Front Cottage", price: 4500, guests: 2 },
    ],
    roomsCount: 6,
    maxGuests: 12,
    bedrooms: 6,
    bathrooms: 6,
    amenities: [
      "Free WiFi",
      "Air Conditioning",
      "Beach Access",
      "Free Parking",
      "Outdoor Seating",
      "Beachside Cafe",
      "Daily Housekeeping",
      "Caretaker on Site",
    ],
    highlights: [
      "Right on serene, unspoilt Agonda Beach",
      "Spectacular sunsets from your veranda",
      "Quiet, intimate, perfect for couples",
      "Great value beachfront escape",
    ],
    tags: ["Beachfront", "Budget", "South Goa", "Agonda", "Couple"],
    nearbyAttractions: [
      "Agonda Beach – 0.1 km",
      "Cola Beach – 6 km",
      "Palolem Beach – 9 km",
      "Cabo de Rama Fort – 12 km",
    ],
    typeLabel: "South Goa Stays",
    typeUrl: "/south-goa-stays",
    featured: false,
  },
]

function longDescription(s) {
  const kind = s.type === "villa" ? "villa" : s.type === "resort" ? "resort" : s.type === "cottage" ? "cottage" : "homestay"
  return [
    `${s.name} is a ${s.tagline.toLowerCase().replace(/^a /, "")} set in ${s.area}. ${s.description_intro || ""}`.trim(),
    `Designed in the warm, textured style that defines the best of Goa, the ${kind} blends earthy materials, natural light and lush surroundings to create a stay that feels both private and effortlessly relaxed. Every space has been considered with the traveller in mind — from generous living areas to thoughtfully equipped bedrooms.`,
    `Located just ${s.nearestBeach.toLowerCase()}, ${s.name} puts you within easy reach of Goa's finest beaches, restaurants and attractions while remaining a calm retreat to return to each evening. The nearest airport is ${s.nearestAirport.toLowerCase()}, making arrivals and departures simple.`,
    `As an independent broker with over eight years of experience across Goa, Goa Beach Stays personally vets every property we list. To check availability, dates and the best rate for ${s.name}, simply send us a WhatsApp message or give us a call — we will take care of the rest.`,
  ].join("\n\n")
}

const stays = seeds.map((s, i) => {
  const id = `stay-${String(i + 1).padStart(3, "0")}`
  const p = pricing(s.rooms)
  const seasonMax = Math.max(...p.season.roomTypes.map((r) => r.pricePerNight))
  const stay = {
    id,
    slug: s.slug,
    type: s.type,
    category: s.category,
    name: s.name,
    tagline: s.tagline,
    location: {
      area: s.area,
      district: s.district,
      region: s.district,
      address: s.address,
      coordinates: { lat: s.lat, lng: s.lng },
      nearestBeach: s.nearestBeach,
      nearestAirport: s.nearestAirport,
      postalCode: s.postalCode,
    },
    pricing: p,
    rooms: s.roomsCount,
    maxGuests: s.maxGuests,
    bedrooms: s.bedrooms,
    bathrooms: s.bathrooms,
    amenities: s.amenities,
    highlights: s.highlights,
    description: {
      short: `${s.tagline}. ${s.name} sits ${s.nearestBeach.toLowerCase()} in ${s.area}, offering a warm, private Goa escape with ${s.amenities[0].toLowerCase()} and more. Book by WhatsApp.`,
      long: longDescription(s),
    },
    images: {
      cover: `/images/stays/${s.slug}/cover.png`,
      gallery: gallery(s.slug),
      ...(s.type !== "homestay" ? {} : {}),
    },
    tags: s.tags,
    nearbyAttractions: s.nearbyAttractions,
    faqs: [
      {
        question: `How far is ${s.name} from the beach?`,
        answer: `${s.name} is located ${s.nearestBeach.replace(/.*\(/, "").replace(")", "")} from ${s.nearestBeach.replace(/\s*\(.*\)/, "")}, one of the area's most loved beaches.`,
      },
      {
        question: `What are the check-in and check-out times?`,
        answer: `Check-in is at 12:00 PM and check-out is at 11:00 AM. Early check-in and late check-out can be arranged on request, subject to availability.`,
      },
      {
        question: `How do I book ${s.name}?`,
        answer: `Bookings are enquiry-based. Send us a WhatsApp message or call us with your dates and number of guests, and we will confirm availability and the best rate for your stay.`,
      },
      {
        question: `Are peak-season rates different?`,
        answer: `Yes. During Goa's peak season (November, December and January) rates are typically around double the standard rate. Both rates are shown transparently on this page.`,
      },
    ],
    reviews: reviewsFor(s.name),
    vacationRentalSchema: true,
    breadcrumbs: breadcrumbs(s, s.typeLabel, s.typeUrl),
    seo: {
      metaTitle: `${s.name} ${s.area.split(", ").pop()} | Goa Beach Stays`.slice(0, 60),
      metaDescription:
        `Book ${s.name} in ${s.area}. ${s.highlights[0]}. Standard from ₹${p.displayPrice.toLocaleString("en-IN")}/night | Season from ₹${(p.displayPrice * 2).toLocaleString("en-IN")}/night. WhatsApp enquiry.`.slice(
          0,
          160,
        ),
      focusKeyword: `${s.name.toLowerCase()} ${s.area.split(", ").pop().toLowerCase()} goa`,
    },
    contact: { whatsappNumber: WA, callNumber: WA },
    featured: s.featured,
    active: true,
    publishedAt: "2025-01-10",
    priceRange: `₹${p.displayPrice.toLocaleString("en-IN")} – ₹${seasonMax.toLocaleString("en-IN")} per night`,
  }
  if (s.type !== "homestay") stay.images.video = "" // optional, left blank for placeholder
  return stay
})

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, JSON.stringify(stays, null, 2))
console.log(`Wrote ${stays.length} stays to ${OUT}`)
